-- Create store_locations table
CREATE TABLE IF NOT EXISTS "store_locations" (
  "id" SERIAL PRIMARY KEY,
  "name" TEXT NOT NULL,
  "city" TEXT NOT NULL,
  "address" TEXT NOT NULL,
  "full_address" TEXT NOT NULL,
  "phone" TEXT NOT NULL,
  "hours" TEXT NOT NULL,
  "closed_days" TEXT DEFAULT '',
  "image" TEXT NOT NULL,
  "lat" TEXT NOT NULL,
  "lng" TEXT NOT NULL,
  "google_place_id" TEXT DEFAULT '',
  "apple_maps_link" TEXT DEFAULT '',
  "map_embed" TEXT NOT NULL,
  "email" TEXT DEFAULT '',
  "store_code" TEXT DEFAULT '',
  "opening_hours" JSONB NOT NULL,
  "services" JSONB NOT NULL,
  "accepted_payments" JSONB NOT NULL,
  "area_served" JSONB NOT NULL,
  "public_transit" TEXT DEFAULT '',
  "parking" TEXT DEFAULT '',
  "year_established" INTEGER NOT NULL,
  "price_range" TEXT NOT NULL,
  "social_profiles" JSONB,
  "description" TEXT NOT NULL,
  "neighborhood_info" TEXT DEFAULT '',
  "amenities" JSONB NOT NULL,
  "created_at" TIMESTAMP DEFAULT NOW() NOT NULL,
  "updated_at" TIMESTAMP DEFAULT NOW() NOT NULL
);